### ISSUE TITLE
Issue on parquet input 

### ISSUE THREAD

**Issue by aquiire** [felixfung/InfoFlow#5]
Looks like parquet files are searched in `hdfs` rather than the normal `fs`, i.e. looking for `hdfs://nameservice1/user/user1/JsonObj(/path/to/node.parquet)` rather than `/path/to/node.parquet`

`config.json`:
```
{
  "Graph": "data.parquet",
  "spark configs": {
    "Master": "yarn",
    "num executors": "10",
    "executor cores": "8",
    "driver memory": "10G",
    "executor memory": "2G"
  },
  "PageRank": {
    "tele": 0.15,
    "error threshold factor": 20
  },
  "Community Detection": {
    "name": "InfoFlow",
        "merge direction": "symmetric"
  },
  "log": {
    "log path": "Output/log.txt",
    "Parquet path": "",
    "RDD path": "",
    "txt path": "Output/vertex.txt",
    "Full Json path": "",
    "Reduced Json path": "Output/graph.json",
    "debug": false
  }
}

```

`data.parquet`

```
{
    "Vertex File": "/path/to/node.parquet",
    "Edge File": "/path/to/edge.parquet"
}

```

Error:

```text
Exception in thread "main" org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://nameservice1/user/user1/JsonObj(/path/to/node.parquet);
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:360)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:348)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:348)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
        at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:559)
        at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:543)
        at ParquetReader$.apply(parquetreader.scala:21)
        at GraphReader$.apply(graphreader.scala:17)
        at InfoFlowMain$.readGraph(main.scala:107)
        at InfoFlowMain$.main(main.scala:38)
        at InfoFlowMain.main(main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by aquiire** [comment]
Since `sqlContext.read.parquet`is meant to search in `hdfs`, closing the issue.
